version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    parallelism: 9
    working_directory: /go/src/github.com/tendermint/tendermint
    steps:
      - checkout
      - run:
          name: Glob tests
          command: go list github.com/tendermint/tendermint/... | grep -v /vendor/ | circleci tests split
      - run:
          name: Get tools
          environment:
            GOBIN: /go/bin
          command: make get_tools
      - run:
          name: Get dependencies
          environment:
            GOBIN: /go/bin
          command: make get_vendor_deps
      - run:
          name: Run tests
          command: |
            bash test/test_cover.sh
      - run:
          name: Upload test coverage
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt
