version: 2

jobs:
  setup:
    working_directory: /go/src/github.com/tendermint/tendermint
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Get tools
          environment:
            GOBIN: /go/bin
          command: make get_tools
      - run:
          name: Get dependencies
          environment:
            GOBIN: /go/bin
          command: make get_vendor_deps
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/tendermint/tendermint


  go_test:
    working_directory: /go/src/github.com/tendermint/tendermint
    parallelism: 4
    docker:
      - image: circleci/golang:1.10
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: |
            for pkg in $(go list github.com/tendermint/tendermint/... | grep -v /vendor/ | circleci tests split); do
              id=$(basename "$pkg")

              go test -timeout 5m -race -coverprofile=profile_$id.out -covermode=atomic "$pkg"
            done
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/tendermint/tendermint

  upload_coverage:
    working_directory: /go/src/github.com/tendermint/tendermint
    parallelism: 4
    docker:
      - image: circleci/golang:1.10
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Combine profiles
          command: |
            echo "mode: atomic" > coverage.txt
            for prof in $(ls | grep profile); do
              tail -n +2 "$prof" >> coverage.txt
            done
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt

workflows:
  version: 2
  test-and-cover:
    jobs:
      - setup
      - go_test:
          requires:
            - setup
      - upload_coverage:
          requires:
            - go_test
