version: 2

defaults: &defaults
  working_directory: /go/src/github.com/tendermint/tendermint
  docker:
    - image: circleci/golang:1.10.0
  environment:
    GOBIN: /go/src/github.com/tendermint/tendermint/.bin
  
jobs:
  setup_dependencies:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir .bin
      - restore_cache:
          keys:
            - v1-bin-cache
            - v1-pkg-cache
      - run:
          name: tools
          command: make get_tools
      - run:
          name: dependencies
          command: make get_vendor_deps
      - run:
          name: binaries
          command: make install
      - save_cache:
          key: v1-bin-cache
          paths:
            - /go/src/github.com/tendermint/tendermint/.bin
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - save_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/tendermint/tendermint

  setup_profile_workspace:
    <<: *defaults
    steps:
      - run: mkdir -p profiles
      - run: touch profiles/.keep
      - persist_to_workspace:
          root: profiles
          paths:
            - .keep

  setup_abci:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-bin-cache
      - restore_cache:
          key: v1-pkg-cache
      - restore_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Checkout abci
          command: |
            commit=$(bash scripts/dep_utils/parse.sh abci)
            go get -v -u -d github.com/tendermint/abci/...
            cd /go/src/github.com/tendermint/abci
            git checkout "$commit"
      - run:
          working_directory: /go/src/github.com/tendermint/abci
          name: Install abci
          command: |
            export PATH="$GOBIN:$PATH"
            make get_tools
            make get_vendor_deps
            make install
      - save_cache:
          key: v1-bin-cache
          paths:
            - /go/src/github.com/tendermint/tendermint/.bin

  lint:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-bin-cache
      - restore_cache:
          key: v1-pkg-cache
      - restore_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: metalinter
          command: make metalinter

  test_cover:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: profiles
      - restore_cache:
          key: v1-pkg-cache
      - restore_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: tests
          command: |
            for pkg in $(go list github.com/tendermint/tendermint/... | grep -v /vendor/ | circleci tests split --split-by=timings); do
              id=$(basename "$pkg")

              go test -v -timeout 5m -race -coverprofile=profiles/$id.out -covermode=atomic "$pkg"
            done
      - persist_to_workspace:
          root: profiles
          paths:
            - "*.out"

  test_app:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-bin-cache
      - restore_cache:
          key: v1-pkg-cache
      - restore_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends bsdmainutils
      - run:
          name: tests
          command: bash test/app/test.sh

  upload_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: profiles
      - restore_cache:
          key: v1-tree-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: gather
          command: |
            set -ex

            echo "mode: atomic" > coverage.txt
            for prof in $(ls profiles/); do
              tail -n +2 profiles/"$prof" >> coverage.txt
            done
      - run:
          name: upload
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt

workflows:
  version: 2
  test-cover:
    jobs:
      - setup_dependencies
      - setup_profile_workspace
      - setup_abci:
          requires:
            - setup_dependencies
      - lint:
          requires:
            - setup_dependencies
      - test_cover:
          requires:
            - setup_dependencies
            - setup_profile_workspace
      - test_app:
          requires:
            - setup_abci
      - upload_coverage:
          requires:
            - test_cover
